const DEFAULT_START = 0
const DEFAULT_LIMIT = 50
const DEFAULT_ROW_HEIGHT = 23
const DEFAULT_ROW_HANDLE_WIDTH = 70
const ROW_HANDLE_MIN_WIDTH = 30
const ROW_HANDLE_MAX_WIDTH = 200
const DEFAULT_COLUMN_WIDTH = 130
const COLUMN_MIN_WIDTH = 30
const COLUMN_MAX_WIDTH = 1200
const COLUMN_RESIZE_HANDLE_WIDTH = 4

export {
  DEFAULT_START,
  DEFAULT_LIMIT,
  DEFAULT_ROW_HEIGHT,
  DEFAULT_ROW_HANDLE_WIDTH,
  ROW_HANDLE_MIN_WIDTH,
  ROW_HANDLE_MAX_WIDTH,
  DEFAULT_COLUMN_WIDTH,
  COLUMN_MIN_WIDTH,
  COLUMN_MAX_WIDTH,
  COLUMN_RESIZE_HANDLE_WIDTH
}
