const DEFAULT_START = 0
const DEFAULT_LIMIT = 50
const DEFAULT_ROW_HEIGHT = 23
const DEFAULT_ROW_HANDLE_WIDTH = 70
const DEFAULT_COLUMN_WIDTH = 130
const DEFAULT_COLUMN_RESIZE_HANDLE_WIDTH = 4

export {
  DEFAULT_START,
  DEFAULT_LIMIT,
  DEFAULT_ROW_HEIGHT,
  DEFAULT_ROW_HANDLE_WIDTH,
  DEFAULT_COLUMN_WIDTH,
  DEFAULT_COLUMN_RESIZE_HANDLE_WIDTH
}
